export * from './burger.svg'
export * from './cart.svg'
export * from './comparison.svg'
export * from './favorites.svg'
export * from './logo.svg'
export * from './profile.svg'
export * from './search.svg'
